package jagdx;

public class Direct3DCaps {
	public static final int anInt905 = 1048576;
	public static final int anInt906 = 131072;
	public static final int anInt907 = 16777216;
	public static final int anInt908 = 2;
	public static final int anInt909 = 16;
	public static final int anInt910 = 32;
	public static final int anInt911 = 2;
	public static final int anInt912 = 2048;
	public static final int anInt913 = 8192;
	public static final int anInt914 = 16384;
	public static final int anInt915 = 32768;
	public static final int anInt916 = 65536;
	public static final int anInt917 = 2;
	public static final int anInt918 = 8;
	public static final int anInt919 = 64;
	public static final int anInt920 = 512;
	public static final int anInt921 = 33554432;
	public int DeviceType;
	public int AdapterOrdinal;
	public int Caps;
	public int Caps2;
	public int Caps3;
	public int PresentationIntervals;
	public int CursorCaps;
	public int DevCaps;
	public int PrimitiveMiscCaps;
	public int RasterCaps;
	public int ZCmpCaps;
	public int SrcBlendCaps;
	public int DestBlendCaps;
	public int AlphaCmpCaps;
	public int ShadeCaps;
	public int TextureCaps;
	public int TextureFilterCaps;
	public int CubeTextureFilterCaps;
	public int VolumeTextureFilterCaps;
	public int TextureAddressCaps;
	public int VolumeTextureAddressCaps;
	public int LineCaps;
	public int MaxTextureWidth;
	public int MaxTextureHeight;
	public int MaxVolumeExtent;
	public int MaxTextureRepeat;
	public int MaxTextureAspectRatio;
	public int MaxAnisotropy;
	public float MaxVertexW;
	public float GuardBandLeft;
	public float GuardBandTop;
	public float GuardBandRight;
	public float GuardBandBottom;
	public float ExtentsAdjust;
	public int StencilCaps;
	public int FVFCaps;
	public int TextureOpCaps;
	public int MaxTextureBlendStages;
	public int MaxSimultaneousTextures;
	public int VertexProcessingCaps;
	public int MaxActiveLights;
	public int MaxUserClipPlanes;
	public int MaxVertexBlendMatrices;
	public int MaxVertexBlendMatrixIndex;
	public float MaxPointSize;
	public int MaxPrimitiveCount;
	public int MaxVertexIndex;
	public int MaxStreams;
	public int MaxStreamStride;
	public int VertexShaderVersion;
	public int MaxVertexShaderConst;
	public int PixelShaderVersion;
	public float PixelShader1xMaxValue;
	public Direct3DVShaderCaps2_0 VS20Caps = new Direct3DVShaderCaps2_0();
	public Direct3DPShaderCaps2_0 PS20Caps = new Direct3DPShaderCaps2_0();
	public int DevCaps2;
	public int MasterAdapterOrdinal;
	public int AdapterOrdinalInGroup;
	public int NumberOfAdaptersInGroup;
	public int DeclTypes;
	public int NumSimultaneousRTs;
	public int StretchRectFilterCaps;
	public int VertexTextureFilterCaps;
	public int MaxVShaderInstructionsExecuted;
	public int MaxPShaderInstructionsExecuted;
	public int MaxVertexShader30InstructionSlots;
	public int MaxPixelShader30InstructionSlots;

}